### ISSUE TITLE
Raspberry Pi 3Bでcolcon build時にフリーズする

### ISSUE THREAD

**Issue by koshiba2020** [rt-net/raspimouse_ros2_examples#23]
# 不具合の概要
下記ラズパイマウスV3向け参考ウェブサイトにおける
https://rt-net.jp/mobility/archives/13788
raspimouse_ros2_examplesパッケージのインストールする
の手順記述を実行したところ、

# Build & Install
$ cd ~/ros2_ws
$ colcon build --symlink-install
$ source ~/ros2_ws/install/setup.bash

の

$ colcon build --symlink-install

を実行後、処理が途中でフリーズしてしまう。

具体的には、処理3つ目の 
　Starting >>> raspimouse_ros2_examples 
が必ず33%で停止する。

SSH接続でなくラズパイマウスV3のRaspberryPi3に直接モニタを接続して確認したところ、画像の様にSSH接続では表示されなかったメッセージも表示されている。

# 実行環境
Ubuntu18.04
ROS2(dashing)

# ログ・画像
![IMG_0714](https://user-images.githubusercontent.com/68490390/114524500-3db5be80-9c80-11eb-837b-90a8edb3165b.jpeg)

**Comment by ShotaAk** [comment]
使用しているラズベリーパイのバージョンを教えていただけますか？

また、一旦raspimouse_ros2_examplesを削除し、
raspimouseのみをビルドしても同じエラーが発生しますか？

**Comment by koshiba2020** [comment]
> 使用しているラズベリーパイのバージョンを教えていただけますか？
> 
> また、一旦raspimouse_ros2_examplesを削除し、
> raspimouseのみをビルドしても同じエラーが発生しますか？

アールティ社の「ラズパイマウスV3フルセット」に同梱されていた RaspberryPi3 です。
ROS1のLiDAR SLAMを実行した際もデータが詰まり気味でした。3でROS2はきついものなのでしょうか？

一旦削除後に再ビルド試してみます。

**Comment by koshiba2020** [comment]
PC側のUbuntu18.04では、

$ cd ~/ros2_ws/src
$ git clone https://github.com/rt-net/raspimouse_ros2_examples
$ rosdep install -r -y --from-paths . --ignore-src
$ cd ~/ros2_ws
$ colcon build --symlink-install

で、raspimouse_msgg、raspimouse、raspimouse_ros2_examples、３つともビルドできました。
3つ目の raspimouse_ros2_examples は33%で一瞬とまりましたが、十数秒で41%となり100%となりました。


> raspimouseのみをビルド

恐れ入ります。。。
上記３つのうち　raspimouse のみをビルド
の方法が判らずにおります。。。

$ colcon build --symlink-install
を
$ colcon build --symlink-install --packages-select raspimouse
とすればよいのでしょうか？

間違った操作をした場合に、元にもどせるスキルがまだないため確認させてください。

**Comment by koshiba2020** [comment]
> PC側のUbuntu18.04では、
> 
> $ cd ~/ros2_ws/src
> $ git clone https://github.com/rt-net/raspimouse_ros2_examples
> $ rosdep install -r -y --from-paths . --ignore-src
> $ cd ~/ros2_ws
> $ colcon build --symlink-install
> 
> で、raspimouse_msgg、raspimouse、raspimouse_ros2_examples、３つともビルドできました。
> 3つ目の raspimouse_ros2_examples は33%で一瞬とまりましたが、十数秒で41%となり100%となりました。
> 
> > raspimouseのみをビルド
> 
> 恐れ入ります。。。
> 上記３つのうち　raspimouse のみをビルド
> の方法が判らずにおります。。。
> 
> $ colcon build --symlink-install
> を
> $ colcon build --symlink-install --packages-select raspimouse
> とすればよいのでしょうか？
> 
> 間違った操作をした場合に、元にもどせるスキルがまだないため確認させてください。

度々おそれいります。
raspimouse だけのビルドは無事できました。

ubuntu@ubuntu:~$ cd ~/ros2_ws
ubuntu@ubuntu:~/ros2_ws$ ls
build  install  log  src
ubuntu@ubuntu:~/ros2_ws$ colcon build --symlink-install --packages-select raspimouse
Starting >>> raspimouse
Finished <<< raspimouse [3.60s]

Summary: 1 package finished [5.12s]
ubuntu@ubuntu:~/ros2_ws$

**Comment by ShotaAk** [comment]
ご報告ありがとうございます。
PC側ではビルドに成功しているため、パッケージ不具合の可能性は低そうです。

こちらでもRaspberry Pi 3 Bで再現するか確認するため、少々お待ちください。

**Comment by koshiba2020** [comment]
> ご報告ありがとうございます。
> PC側ではビルドに成功しているため、パッケージ不具合の可能性は低そうです。
> 
> こちらでもRaspberry Pi 3 Bで再現するか確認するため、少々お待ちください。

raspimouseビルド時　と　raspimouse_ros2_examplesビルド時の　負荷状況をスクリーンショットしてみました。
なにかの参考になると嬉しいです。
（メモリ不足でしょうか？）

![01_負荷チェック](https://user-images.githubusercontent.com/68490390/114801328-79fb3300-9dd6-11eb-979b-c8fddfc74469.jpg)
![02_raspimouse](https://user-images.githubusercontent.com/68490390/114801340-7cf62380-9dd6-11eb-86eb-41f6e926e17b.jpg)
![03_1つ目実行後](https://user-images.githubusercontent.com/68490390/114801351-8089aa80-9dd6-11eb-8940-1bd0aa5ca83d.jpg)
![04_２つ目実行フリーズ](https://user-images.githubusercontent.com/68490390/114801354-81bad780-9dd6-11eb-90c0-4d4c4ac97a19.jpg)
![05_10分経過](https://user-images.githubusercontent.com/68490390/114801362-83849b00-9dd6-11eb-95dc-c5078098a3f5.jpg)

**Comment by ShotaAk** [comment]
@koshiba2020 こちらの環境でもフリーズが再現しました。

ご報告の通りメモリ不足が原因です。対策として環境変数`MAKEFLAGS=-j1`をセットし、`colcon build`を実行してみてください。

```sh
$ MAKEFLAGS=-j1 colcon build --symlink-install
Starting >>> raspimouse_msgs
[Processing: raspimouse_msgs]                             
[Processing: raspimouse_msgs]                                     
[Processing: raspimouse_msgs]                                          
Finished <<< raspimouse_msgs [1min 36s]                                
Starting >>> raspimouse
[Processing: raspimouse]                                  
[Processing: raspimouse]                                  
Finished <<< raspimouse [1min 20s]                                
Starting >>> raspimouse_ros2_examples
[Processing: raspimouse_ros2_examples]                                 
[Processing: raspimouse_ros2_examples]                                      
[Processing: raspimouse_ros2_examples]                                       
[Processing: raspimouse_ros2_examples]                                       
[Processing: raspimouse_ros2_examples]                                       
[Processing: raspimouse_ros2_examples]                                        
Finished <<< raspimouse_ros2_examples [3min 8s]                               

Summary: 3 packages finished [6min 5s]
```

参考情報：https://answers.ros.org/question/368249/colcon-build-number-of-threads/

**Comment by koshiba2020** [comment]
> ご報告の通りメモリ不足が原因です。対策として環境変数`MAKEFLAGS=-j1`をセットし、`colcon build`を実行してみてください。

実行してみました。

ubuntu@ubuntu:~$ cd ~/ros2_ws
ubuntu@ubuntu:~/ros2_ws$ MAKEFLAGS=-j1 colcon build --symlink-install
Starting >>> raspimouse_msgs
Finished <<< raspimouse_msgs [9.41s]
Starting >>> raspimouse
Finished <<< raspimouse [3.12s]
Starting >>> raspimouse_ros2_examples
[Processing: raspimouse_ros2_examples]
[Processing: raspimouse_ros2_examples]
[Processing: raspimouse_ros2_examples]
[Processing: raspimouse_ros2_examples]
[Processing: raspimouse_ros2_examples]
Finished <<< raspimouse_ros2_examples [2min 51s]
Summary: 3 packages finished [3min 6s]

ビルドが成功しました！

続きましてインストールを実行
ubuntu@ubuntu:~/ros2_ws$ source ~/ros2_ws/install/setup.bash

エラーは表示されず。

続きましてROS2サンプルの一つ目 DualShock3 USB接続でコントロールを実行しようとしますと、、、
ubuntu@ubuntu:~/ros2_ws$ ros2 launch raspimouse_ros2_examples teleop_joy.launch.py joydev:="/dev/input/js0" joyconfig:=dualshock3 mouse:=true
ros2: command not found

となってしまいました。
ひとつ前の記事
https://rt-net.jp/mobility/archives/13403
の
ros2 run raspimouse raspimouse
や
ros2 lifecycle set raspimouse configure
などは問題なく動作し、ブザーをならしたり止めたりできていたのですが？？？

次から次へと恐縮です。。。

**Comment by ShotaAk** [comment]
無事にビルドできてよかったです。

`ros2: command not found` と記載されてますので、
ROS 2の環境をセットアップしていない（`source /opt/ros/dashing/setup.bash`していない）と思われます。ご確認ください。

このIssueは**Raspberry Pi 3Bでcolcon build時にフリーズする** という内容が解決したことで一旦クローズします。
また別の問題が発生した場合は、あたらしくIssueを立ててください。

@koshiba2020 お手数ですが、このIssueのタイトルを「Raspberry Pi 3Bでcolcon build時にフリーズする」に変更していただけないでしょうか？

**Comment by koshiba2020** [comment]
> このIssueのタイトルを「Raspberry Pi 3Bでcolcon build時にフリーズする」に変更していただけないでしょうか？

ありがとうございました！
変更いたしました！
