### ISSUE TITLE
Error: $ rosdep install -r -y --from-paths . --ignore-src

### ISSUE THREAD

**Issue by kamoyuka** [rt-net/raspimouse_ros2_examples#35]
# 不具合の概要
<rtのブログhttps://rt-net.jp/mobility/archives/13788
通りに作業を進めていたのですが、ジョイスティックコントローラの設定でエラーが出てしまいました。>

# 実行環境
- OS: Ubuntu 18.04

# 再現方法

1. '$ cd ~/ros2_ws/src' を実行する
2. '$ git clone https://github.com/rt-net/raspimouse_ros2_examples'  を実行する
3. '$ rosdep install -r -y --from-paths . --ignore-src’ を実行する
4. エラー発生
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
raspimouse_ros2_examples: Cannot locate rosdep definition for [joy_linux]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully

# 期待する動作
<ジョイスティックコントローラを接続したい>

**Comment by Tiryoh** [comment]
@kamoyuka フィードバックありがとうございます。
使用しているROSのディストリビューションはDashingですか？
その場合は[dashing-devel](https://github.com/rt-net/raspimouse_ros2_examples/tree/dashing-devel)ブランチに切り替えてみてください。
git clone時にオプションをつけるか、git clone後のディレクトリでgit checkoutすることで切り替えが可能です。

```sh
# git clone時にブランチ指定
git clone -b $ROS_DISTRO-devel https://github.com/rt-net/raspimouse_ros2_examples

# git clone後にブランチ切り替え
git clone https://github.com/rt-net/raspimouse_ros2_examples
cd raspimouse_ros2_examples
git checkout -b $ROS_DISTRO-devel
```

masterブランチは現在Foxyで動くように開発を進めています。
https://github.com/rt-net/raspimouse_ros2_examples/pull/27 にてDashing以前で使っていた`joy`から`joy_linux`に変えたことにより`rosdep install`がうまく行かなくなっているのだと思います。

**Comment by kamoyuka** [comment]
回答いただきありがとうございます。
ROSのディストリビューションはDashingです。
一度raspimouse_ros2_examplesディレクトリを削除し、ブランチ指定してgit cloneしたところ解決することができました。

`$ git clone -b dashing-devel https://github.com/rt-net/raspimouse_ros2_examples`

**Comment by Tiryoh** [comment]
よかったです。経過報告ありがとうございます！
問題がなければ本Issueのcloseをお願いします。動かしてみてまた質問が出てきましたら別Issueとして作成をお願いします :bow:
