### ISSUE TITLE
Potential deadlock in callbacks in the shutdown sequence of joystick control

### ISSUE THREAD

**Issue by sayali-purdue** [rt-net/raspimouse_ros2_examples#56]
# Describe the bug
In file [joystick_control.py](raspimouse_ros2_examples/joystick_control.py), the client '_client_change_state' will potentially keep waiting indefinitely for the service response at [line 155](https://github.com/rt-net/raspimouse_ros2_examples/blob/bdef32ba4d575385584d8b9519460548d1945ee9/raspimouse_ros2_examples/joystick_control.py#L155), because line 155 is executed as part of the callback function '_callback_joy' of the subscriber '_sub_joy', and both the subscriber and the client belong to the same mutually exclusive callback group (the default callback group of ROS node 'JoyWrapper').

# Environments
Static analysis of source code
- OS: N/A
- Software Version: N/A

# To Reproduce
Static review/inspection of source code

# Expected behavior

# Full log or Screenshots

# Additional context
The callback function of the subscriber '_callback_joy' calls function '_joy_shutdown' which then calls function '_set_mouse_lifecycle_state'. 

At  [line 155](https://github.com/rt-net/raspimouse_ros2_examples/blob/bdef32ba4d575385584d8b9519460548d1945ee9/raspimouse_ros2_examples/joystick_control.py#L155) in function  '_set_mouse_lifecycle_state', the future object of the asynchronous service call will not be set with the service response. 

This is because future object has the same callback group as the client '_client_change_state' that makes the asynchronous service call. In rclpy, 'call_async' API that is used to call the service internally defines future_done_callback and waits for it to finish execution. future_done_callback belongs to the callback group of the future object, i.e., the callback group of the client. The callback '_callback_joy' belongs to the callback group of the subscriber. Since the callback group is not explicitly defined for the subscriber at [line 123](https://github.com/rt-net/raspimouse_ros2_examples/blob/bdef32ba4d575385584d8b9519460548d1945ee9/raspimouse_ros2_examples/joystick_control.py#L123) and for the client at [line 134](https://github.com/rt-net/raspimouse_ros2_examples/blob/bdef32ba4d575385584d8b9519460548d1945ee9/raspimouse_ros2_examples/joystick_control.py#L134), they both have the same callback group, i.e., the default mutually exclusive callback group of the ROS node 'JoyWrapper'. Callbacks of the mutually exclusive callback group cannot execute in parallel. Therefore,  future_done_callback will not be executed until the subscriber callback '_callback_joy' finishes its execution. And hence, 'spin_until_future_complete' at line 155 will keep spinning.

**Comment by YusukeKato** [comment]
@sayali-purdue
Thank you for reporting the bug!
We will proceed with fixing #56 and #57.

**Comment by YusukeKato** [comment]
@sayali-purdue 
This issue have been fixed.
We appreciate your report!
