### ISSUE TITLE
Node added to multiple executors at the same time

### ISSUE THREAD

**Issue by sayali-purdue** [rt-net/raspimouse_ros2_examples#57]
# Describe the bug
In file [joystick_control.py](https://github.com/rt-net/raspimouse_ros2_examples/issues/raspimouse_ros2_examples/joystick_control.py), the ROS node 'JoyWrapper' is added to two executors at the same time during 'rclpy.spin' at [line 400](https://github.com/rt-net/raspimouse_ros2_examples/blob/bdef32ba4d575385584d8b9519460548d1945ee9/raspimouse_ros2_examples/joystick_control.py#L400) and during 'rclpy.spin_until_future_complete' at [line 155](https://github.com/rt-net/raspimouse_ros2_examples/blob/bdef32ba4d575385584d8b9519460548d1945ee9/raspimouse_ros2_examples/joystick_control.py#L155C9-L155C41). In rclpy, if a node is added to the executor Y when the node was already added to the executor X  the node is removed from the executor X. So, if the program control reaches back to the blocking spinning of executor X i.e. 'spin' API, executor X no longer handles callbacks of the node.

# Environments
Static analysis of source code

- OS: N/A
- Software Version: N/A

# To Reproduce
Static review/inspection of source code

# Expected behavior

# Full log or Screenshots

# Additional context
The callback function of the subscriber '_callback_joy' calls function '_joy_shutdown' which then calls function '_set_mouse_lifecycle_state'.

At [line 155](https://github.com/rt-net/raspimouse_ros2_examples/blob/bdef32ba4d575385584d8b9519460548d1945ee9/raspimouse_ros2_examples/joystick_control.py#L155) in function '_set_mouse_lifecycle_state', 'rclpy.spin_until_future_complete' adds the 'JoyWrapper' node to the custom executor defined in the same function.

Note that the '_callback_joy' is executed via 'rclpy.spin' at [line 400](https://github.com/rt-net/raspimouse_ros2_examples/blob/bdef32ba4d575385584d8b9519460548d1945ee9/raspimouse_ros2_examples/joystick_control.py#L400). This is a blocking spin call. At the beginning of this spin call, the 'JoyWrapper' node is added to the global executor, as no custom executor is specified. At line 155 (describe above), when the 'JoyWrapper' node is added to the custom executor, the 'JoyWrapper' node is removed from the global executor. Therefore, if the  '_callback_joy' finishes its execution and returns to the blocking spin call at line 400, the spin call will not execute callbacks of the 'JoyWrapper' node.

**Comment by YusukeKato** [comment]
@sayali-purdue
Thank you for reporting the bug.
We will proceed with fixing this issue.

**Comment by YusukeKato** [comment]
@sayali-purdue 
This issue have been fixed.
We appreciate your report!
